### ISSUE TITLE
Estrutura de Log

### ISSUE THREAD

**Issue by pabrrs** [b2wads/nodejs-boilerplate#11]
Precisamos definir alguns pontos em relação ao logger que será utilizado no boilerplate. Assim sugiro os seguintes tópicos para debatermos: 

- Definir configurações iniciais
    - Quais configurações teremos em variáveis de ambiente
- Formato de saída do log
- Métodos personalizados sobre o logger
- Informações a serem loggadas

----

O que temos hoje iniciado no projeto [admatic-products-feed](https://github.com/b2wads/admatic-products-feed):

#### Configurações iniciais
```js
logger = pino({
  useLevelLabels: true,
  ...options
  },
  loggerConfig.logFile
)
```

- `options`: Configurações adicionais do contexto onde o logger está sendo instanciado: E.g.:

```js
const logger = require('client/logger')({
     foo: 'bar'
})
```

- `logConfig.logFile`: Variável de ambiente `ADMATIC_LOG_FILE`, contendo o nome do arquivo onde será feita a saída de log, removendo a saída padrão (stdout/stderr)

#### Formato de saída do log:

```js
{
  "level":"info",
  "time":1559579635413,
  "pid":13975,
  "hostname":"BRRJOBITANL1993",
  "event_name":"ProductService.sync",
  "msg":{
    // informações a serem loggadas
  },
  "v":1
}
```

#### Métodos personalizados sobre o logger

- `logger.exception(err: Error, extraInfo?)`: Método que recebe uma exception e serializa sua informação.

```js
const logger = require('client/logger')()
logger.exception(err, extraInfo)
``` 
output:
```json
{
  "msg": {
    "error": {
      "message": "action is a required field",
      "type": "ValidationError",
      "stack_trace": [
        "ValidationError: action is a required field",
        "    at createError (/home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/yup/lib/util/createValidation.js:64:35)",
        "    at Object.nextFn (/home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/yup/lib/util/createValidation.js:113:108)",
        "    at /home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/synchronous-promise/index.js:188:29",
        "    at Array.forEach (<anonymous>)",
        "    at SynchronousPromise._runResolutions (/home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/synchronous-promise/index.js:185:19)",
        "    at SynchronousPromise.then (/home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/synchronous-promise/index.js:61:10)",
        "    at validate (/home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/yup/lib/util/createValidation.js:112:44)",
        "    at /home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/yup/lib/mixed.js:247:18",
        "    at Array.map (<anonymous>)",
        "    at Object.nextFn (/home/paulo.alfredo/Projects/b2w/admatic-products-feed/node_modules/yup/lib/mixed.js:246:35)"
      ]
    }
  }
}
```

#### Informações a serem logadas

- `timestamp`: Data e hora do momento quando o log foi chamado
- `msg`: Informações do contexto, ação, método, etc...
- `event_name`: Nome do método que está sendo chamado. e.g: `FooController.methodName`

O que acham dessa estrutura ? Quais sugestões ? Comentem :smiley:

@b2wads/b2wads 

----

p.s.: As threads que motivaram essa issue:
https://github.com/b2wads/admatic-products-feed/pull/2#discussion_r289136286
https://github.com/b2wads/admatic-products-feed/pull/2#discussion_r289135667
https://github.com/b2wads/admatic-products-feed/pull/2#discussion_r289164354

**Comment by daltonmatos** [comment]
@pabarros,

respondendo em termos gerais:

- Sugiro, inicialmente, uma env: `B2WADS_LOG_LEVEL`. Como não temos um projeto de logger separado podemos usar o prefixo `B2WADS` mesmo. Tendo um projeto separado poderíamos usar o nome do projeto como prefixo, mas isso fica pro futuro. =D
- Acho que não devemos ter suporte a log em arquivo, at all;
- Métodos do logger acho que devem ser um para cada loglevel: `.info(), .warning(), .error(), .debug(), .exception()`; Todos esses métodos, com exceção do `.exception()` deveriam revceber apenas um parametro, que é o objeto a ser logado.
- Sobre as infos a serem logadas, o que eu acho:
  - data/hora mm formato [iso8601](https://pt.wikipedia.org/wiki/ISO_8601), **com** informação de timezone. Já tivemos problemas com indexação de logs que tinham data mas não diziam de qual timezone nem se era UTC ou não.
  - Linha de código onde o log foi gerado;
  - Nome do método onde o log foi gerado. Acho que o "event-name" deve ser escolhido pelo dev que está gerando o código.
  - Level que está sendo usado
  - Path absoluto do arquivo onde o log foi gerado.
- Em relação ao formado. Acho que poderíamos ter a opção de gerar tudo na raiz do json ou de termos nosso objeto dentro de uma key qualquer (escolhida em tempo de config do logger).


Em relação do método `.exception()`, está perfeito.

**Comment by diogommartins** [comment]
> @pabarros,
> 
> respondendo em termos gerais:
> 
> * Sugiro, inicialmente, uma env: `B2WADS_LOG_LEVEL`. Como não temos um projeto de logger separado podemos usar o prefixo `B2WADS` mesmo. Tendo um projeto separado poderíamos usar o nome do projeto como prefixo, mas isso fica pro futuro. =D
> * Acho que não devemos ter suporte a log em arquivo, at all;
> * Métodos do logger acho que devem ser um para cada loglevel: `.info(), .warning(), .error(), .debug(), .exception()`; Todos esses métodos, com exceção do `.exception()` deveriam revceber apenas um parametro, que é o objeto a ser logado.

Compartilhando a título de curioside. Tanto o pino quanto o winston oferentce mais níveis de log que esses:
* https://github.com/winstonjs/winston#logging-levels
* https://github.com/pastjean/pino-text-level-transport/blob/master/index.js#L9

> * Sobre as infos a serem logadas, o que eu acho:
>   
>   * data/hora mm formato [iso8601](https://pt.wikipedia.org/wiki/ISO_8601), **com** informação de timezone. Já tivemos problemas com indexação de logs que tinham data mas não diziam de qual timezone nem se era UTC ou não.
>   * Linha de código onde o log foi gerado;
>   * Nome do método onde o log foi gerado. Acho que o "event-name" deve ser escolhido pelo dev que está gerando o código.
>   * Level que está sendo usado
>   * Path absoluto do arquivo onde o log foi gerado.
> * Em relação ao formado. Acho que poderíamos ter a opção de gerar tudo na raiz do json ou de termos nosso objeto dentro de uma key qualquer (escolhida em tempo de config do logger).
> 
> Em relação do método `.exception()`, está perfeito.

**Comment by daltonmatos** [comment]
Penso que devemos definit o seguinte:

- Como queremos configurar uma instância do nosso logger?
- Como vamos importr nosso logger? Por enquanto temos: `const logger = require("...")`. Voto nessa como versão final.
- Como queremos escrever nossas linhas de código que chamam o logger? Vejo opções:
  - `await logger.info({...})`
  -  `logger.info({...})`
- Teremos a opção de colocar os campos do objeto logado na raiz do json? Ou colocaremos **sempre** abaixo de uma key default?
  - Se tivermos um key default, poderemos mudá-la via ENV?
- Quais serão os levels que usaremos?

Acho que definindo isso, poderemos seguir para próximas definições como:

- Quais campos já são incluídos por padrão?
- Qual o formato de cada campo?

O que acham?

**Comment by pabarros** [comment]
> * Como queremos configurar uma instância do nosso logger?
> 

Hoje instanciamos apenas setando nível de log como 'info' (ou o que está definido na variável de ambiente `B2WADS_LOG_LEVEL`) e utilizar as labels dos níveis de log:

```js
const logger = pino({
  useLevelLabels: true,
  level: loggerConfig.logLevel
})
```

Até o momento, isso tem sido o suficiente. 

> * Como vamos importr nosso logger? Por enquanto temos: `const logger = require("...")`. Voto nessa como versão final.

Gosto desse modo tbm :+1: 

> * Como queremos escrever nossas linhas de código que chamam o logger? Vejo opções:
>   
>   * `await logger.info({...})`
>   * `logger.info({...})`
> 

Considerando o que estamos utilizando, hoje apenas é possível utilizar `logger.info({...})`. Porém isso é extensível para o futuro, a possibilidade de utilizar `await`.

> * Teremos a opção de colocar os campos do objeto logado na raiz do json? Ou colocaremos **sempre** abaixo de uma key default?
>   
>   * Se tivermos um key default, poderemos mudá-la via ENV?

Faz sentido mudar a key padrão nos logs ? Acredito que podemos definir uma key para todas as estruturas e ter ela como padrão para todo mundo. Voto por `message`.

> * Quais serão os levels que usaremos?

Como já conversado (https://github.com/b2wads/admatic-products-feed/pull/2#discussion_r291991472, https://github.com/b2wads/admatic-products-feed/pull/2#discussion_r290799223) por padrão é habilitado o nível de log `info`, para ambiente de desenvolvimento é habilitado `debug` e em produção é configurável via ENV var. 
Gosto desse modelo e acho que funciona bem.

**Comment by daltonmatos** [comment]
> Faz sentido mudar a key padrão nos logs ? Acredito que podemos definir uma key para todas as estruturas e ter ela como padrão para todo mundo. Voto por `message`.

Beleza, definam o nome e vamos nesse caminho mesmo. Lembrando que "message" agora é um objeto complexo e não mais uma string simples.

> Considerando o que estamos utilizando, hoje apenas é possível utilizar logger.info({...}). Porém isso é extensível para o futuro, a possibilidade de utilizar await.

Certo, mas desde agora já vamos ter que escrever "wrappers" em torno dos métodos do pino, certo? Afinal não é o pino que tem aquela interface estranha de passar dois parametros pros métodos de log? Meu questionamento é: Se já vamos ter que fazer um wrap (caso isso seja confirmado) queria que vocês pensassem se já vale a pena fazer esse wrap exigindo `await` nas chamadas. Pensem nisso.

**Comment by pabrrs** [comment]
Adicionamos a lib [`@b2wads/logger`](https://www.npmjs.com/package/@b2wads/logger) na PR #54
