### ISSUE TITLE
Adicionar `/bin/www` usando NODE_PORT para ler a porta

### ISSUE THREAD

**Issue by daltonmatos** [b2wads/nodejs-boilerplate#9]
Vamos usar um env padrão para todos os projetos no momento de escolher a porta que será aberta.

Não podemos usar `PORT` pois nosso orquestrador injeta essa var para as aplicações, então não temos como controlar o valor que estará ali.

**Comment by pabarros** [comment]
Podemos utilizar `NODE_PORT` com default `3000`, como já é padrão de algumas apps.

**Comment by pabarros** [comment]
Feature adicionada na PR https://github.com/b2wads/nodejs-boilerplate/pull/17
